apiVersion: v1
kind: Service
metadata:
  name: coredns-metrics
  namespace: kube-system
  labels:
    app: coredns
spec:
  selector:
    k8s-app: kube-dns
  ports:
    - name: metrics
      port: 9153
      targetPort: 9153
      protocol: TCP
