apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Release.Name }}-prometheus-server
        isDefault: true
        editable: false
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://{{ .Release.Name }}-loki-gateway
        editable: false
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://{{ .Release.Name }}-tempo:3200
        isDefault: false
        editable: false
        jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: prometheus
          tracesToLogs:
            datasourceUid: loki
            mappedTags:
              - key: service.name
                value: service_name
            mapTagNamesEnabled: true
            spanStartTimeShift: "-5m"
            spanEndTimeShift: "5m"
            filterByTraceID: true
            filterBySpanID: true
          tracesToMetrics:
            datasourceUid: prometheus
          search:
            hide: false
          nodeGraph:
            enabled: true
