{{- if not .Values.grafana.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | quote }}
  admin-password: {{ .Values.grafana.adminPassword | quote }}
{{- end }}
