{{- if (.Values.createNamespace | default false) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: monitoring-platform
    app.kubernetes.io/managed-by: Helm
{{- end }}
