{
 "title": "Ingress Nginx / Overview",
 "description": "A dashboard that monitors Ingress-nginx. It is created using the (Ingress-Nginx-mixin)[https://github.com/adinhodovic/ingress-nginx-mixin]",
 "tags": [
  "ingress-nginx",
  "ingress-nginx-mixin"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash, cluster)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster=~\"$cluster\"}, job)"
    }
   },
   {
    "name": "controller_namespace",
    "label": "Controller Namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster=~\"$cluster\", job=~\"$job\"}, controller_namespace)"
    }
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster=~\"$cluster\", job=~\"$job\", controller_namespace=~\"$controller_namespace\"}, controller_class)"
    }
   },
   {
    "name": "controller",
    "label": "Controller Pod",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster=~\"$cluster\", job=~\"$job\", controller_namespace=~\"$controller_namespace\", controller_class=~\"$controller_class\"}, controller_pod)"
    }
   },
   {
    "name": "ingress_namespace",
    "label": "Ingress Target Namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "ingress",
    "label": "Ingress Name",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{cluster=~\"$cluster\", namespace=~\"$ingress_namespace\"}, ingress)"
    }
   },
   { "name": "error_codes", "label": "error_codes", "query": "4,5" }
  ]
 },
 "panels": [
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controller Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    irate(\n      nginx_ingress_controller_requests{\n        cluster=\"$cluster\",\n        job=~\"$job\",\n        namespace=~\"$ingress_namespace\",\n        controller_pod=~\"$controller\",\n        controller_class=~\"$controller_class\"\n      }[$__rate_interval]\n    )\n  ), 0.001\n)\n"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  avg_over_time(\n    nginx_ingress_controller_nginx_process_connections{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      controller_pod=~\"$controller\",\n      controller_class=~\"$controller_class\",\n      controller_namespace=~\"$controller_namespace\"\n    }[$__rate_interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non $error_codes-xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_requests{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      controller_pod=~\"$controller\",\n      controller_class=~\"$controller_class\",\n      namespace=~\"$ingress_namespace\",\n      namespace=~\"$ingress_namespace\",\n      status!~\"[$error_codes].*\"\n    }[$__rate_interval]\n  )\n)\n/\nsum(\n  rate(\n    nginx_ingress_controller_requests{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      controller_pod=~\"$controller\",\n      controller_class=~\"$controller_class\",\n      namespace=~\"$ingress_namespace\",\n      namespace=~\"$ingress_namespace\"\n    }[$__rate_interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  irate(\n    nginx_ingress_controller_success{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      controller_pod=~\"$controller\",\n      controller_class=~\"$controller_class\",\n      controller_namespace=~\"$controller_namespace\"\n    }[$__rate_interval]\n  )\n) * 60\n"
    }
   ]
  },
  {
   "title": "Last Config Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  nginx_ingress_controller_config_last_reload_successful{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    controller_pod=~\"$controller\",\n    controller_namespace=~\"$controller_namespace\"\n  } == 0\n) OR vector(0)\n"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    irate(\n      nginx_ingress_controller_requests{\n        cluster=\"$cluster\",\n        job=~\"$job\",\n        controller_pod=~\"$controller\",\n        controller_class=~\"$controller_class\",\n        controller_namespace=~\"$controller_namespace\",\n        ingress=~\"$ingress\",\n        namespace=~\"$ingress_namespace\"\n      }[$__rate_interval]\n    )\n  ) by (cluster, namespace, ingress), 0.001\n)\n",
     "legendFormat": "{{ cluster }}/{{ namespace }}/{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non $error_codes-xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_requests{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      controller_pod=~\"$controller\",\n      controller_class=~\"$controller_class\",\n      namespace=~\"$ingress_namespace\",\n      namespace=~\"$ingress_namespace\",\n      ingress=~\"$ingress\",\n      status!~\"[$error_codes].*\"\n    }[$__rate_interval]\n  )\n) by (cluster, namespace, ingress)\n/\nsum(\n  rate(\n    nginx_ingress_controller_requests{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      controller_pod=~\"$controller\",\n      controller_class=~\"$controller_class\",\n      namespace=~\"$ingress_namespace\",\n      namespace=~\"$ingress_namespace\",\n      ingress=~\"$ingress\"\n    }[$__rate_interval]\n  )\n) by (cluster, namespace, ingress)\n",
     "legendFormat": "{{ cluster }}/{{ namespace }}/{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50, sum(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        cluster=\"$cluster\",\n        job=~\"$job\",\n        ingress!=\"\",\n        controller_pod=~\"$controller\",\n        controller_class=~\"$controller_class\",\n        controller_namespace=~\"$controller_namespace\",\n        namespace=~\"$ingress_namespace\",\n        ingress=~\"$ingress\"\n      }[$__rate_interval]\n    )\n  ) by (le, cluster, namespace, ingress)\n)\n"
    },
    {
     "expr": "histogram_quantile(\n  0.90, sum(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        cluster=\"$cluster\",\n        job=~\"$job\",\n        ingress!=\"\",\n        controller_pod=~\"$controller\",\n        controller_class=~\"$controller_class\",\n        controller_namespace=~\"$controller_namespace\",\n        namespace=~\"$ingress_namespace\",\n        ingress=~\"$ingress\"\n      }[$__rate_interval]\n    )\n  ) by (le, cluster, namespace, ingress)\n)\n"
    },
    {
     "expr": "histogram_quantile(\n  0.99, sum(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        cluster=\"$cluster\",\n        job=~\"$job\",\n        ingress!=\"\",\n        controller_pod=~\"$controller\",\n        controller_class=~\"$controller_class\",\n        controller_namespace=~\"$controller_namespace\",\n        namespace=~\"$ingress_namespace\",\n        ingress=~\"$ingress\"\n      }[$__rate_interval]\n    )\n  ) by (le, cluster, namespace, ingress)\n)\n"
    },
    {
     "expr": "sum(\n  irate(\n    nginx_ingress_controller_request_size_sum{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      ingress!=\"\",\n      controller_pod=~\"$controller\",\n      controller_class=~\"$controller_class\",\n      controller_namespace=~\"$controller_namespace\",\n      namespace=~\"$ingress_namespace\",\n      ingress=~\"$ingress\"\n    }[$__rate_interval]\n  )\n) by (cluster, namespace, ingress)\n"
    },
    {
     "expr": "sum(\n  irate(\n    nginx_ingress_controller_response_size_sum{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      ingress!=\"\",\n      controller_pod=~\"$controller\",\n      controller_class=~\"$controller_class\",\n      controller_namespace=~\"$controller_namespace\",\n      namespace=~\"$ingress_namespace\",\n      ingress=~\"$ingress\"\n    }[$__rate_interval]\n  )\n) by (cluster, namespace, ingress)\n"
    }
   ]
  },
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Ingress Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  nginx_ingress_controller_ssl_expire_time_seconds{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    pod=~\"$controller\"\n  }\n) by (host) - time()\n"
    }
   ]
  }
 ]
}